/* ═══ ALL QUEST DATA — ordered by spreadsheet "Order Author" column ═══ */
/* Quest object shape:
   id, name, type ('Main Quest'|'Side Quest'|'Contract'|'Treasure Hunt'|'Race'|'Event'),
   region, when (WHEN TO DO), note (COMMENT), from ('Wild Hunt Main'|'Hearts of Stone'|'Blood and Wine')
*/

const QUESTS = [
  // ── WHITE ORCHARD ──────────────────────────────────────────────────
  {id:'q1',  name:'Kaer Morhen',           type:'Main Quest',    region:'Kaer Morhen',  from:'Wild Hunt', note:"First mission after intro scenes: Geralt's dream of young Ciri."},
  {id:'q2',  name:'Lilac and Gooseberries',type:'Main Quest',    region:'White Orchard',from:'Wild Hunt', note:'MAKE SURE YOU PICK UP THE CRYSTAL SKULL! First mission after arriving at White Orchard.'},
  {id:'q3',  name:'Twisted Firestarter',   type:'Side Quest',    region:'White Orchard',from:'Wild Hunt', when:'ASAP'},
  {id:'q4',  name:'A Frying Pan, Spick and Span', type:'Side Quest', region:'White Orchard', from:'Wild Hunt', when:'ASAP'},
  {id:'q5',  name:'Missing in Action',     type:'Side Quest',    region:'White Orchard',from:'Wild Hunt', when:'ASAP'},
  {id:'q6',  name:'Deserter Gold',         type:'Treasure Hunt', region:'White Orchard',from:'Wild Hunt', note:"Find the spy's notes by the corpse."},
  {id:'q7',  name:'Dirty Funds',           type:'Treasure Hunt', region:'White Orchard',from:'Wild Hunt', note:'Notes in the crate in the campsite guarded by wolves.'},
  {id:'q8',  name:'Temerian Valuables',    type:'Treasure Hunt', region:'White Orchard',from:'Wild Hunt', note:"West of Mill — orders in a locked crate hidden under water."},
  {id:'q9',  name:'Scavenger Hunt: Viper School Gear', type:'Treasure Hunt', region:'White Orchard', from:'Wild Hunt', note:"Letter to be found near Kolgrim's corpse in the crypt."},
  {id:'q10', name:'Precious Cargo',        type:'Side Quest',    region:'White Orchard',from:'Wild Hunt', when:'ASAP'},
  {id:'q11', name:"On Death's Bed",        type:'Side Quest',    region:'White Orchard',from:'Wild Hunt', when:'ASAP', note:"Only available before unlocking Velen — finish it before returning to Vesemir after collecting the griffin reward."},
  {id:'q12', name:'Contract: Devil by the Well', type:'Contract', region:'White Orchard', from:'Wild Hunt'},
  {id:'q13', name:'The Beast of White Orchard', type:'Main Quest', region:'White Orchard', from:'Wild Hunt', when:'See Comment', note:'If you want to experience the full mission, do NOT explore too much beforehand!'},
  {id:'q14', name:'The Incident at White Orchard', type:'Main Quest', region:'White Orchard', from:'Wild Hunt'},
  {id:'q15', name:'Imperial Audience',     type:'Main Quest',    region:'Vizima',       from:'Wild Hunt'},

  // ── VELEN EARLY ────────────────────────────────────────────────────
  {id:'q16', name:'The Nilfgaardian Connection', type:'Main Quest', region:'Velen', from:'Wild Hunt'},
  {id:'q17', name:'Event: At the Mercy of Strangers I', type:'Event', region:'Velen', from:'Wild Hunt', when:'ASAP', note:'Go west from Mulbrydale towards the river — follow the screaming to learn the tale of John Verdun.'},
  {id:'q18', name:"Event: Crow's Perch Fight", type:'Event', region:'Velen', from:'Wild Hunt', when:'ASAP', note:"Only shows if you killed the Baron's Men at the inn in The Nilfgaardian Connection."},
  {id:'q19', name:'Bloody Baron',          type:'Main Quest',    region:'Velen',        from:'Wild Hunt'},
  {id:'q20', name:"Ciri's Story: The King of the Wolves", type:'Main Quest', region:'Velen', from:'Wild Hunt'},
  {id:'q21', name:"Ciri's Room",           type:'Side Quest',    region:'Velen',        from:'Wild Hunt', when:'Early in story', note:"Must be done before going to the Isle of Mists — best done after you searched the castle during Family Matters."},
  {id:'q22', name:'Event: Face Me if You Dare! I', type:'Event', region:'Velen', from:'Wild Hunt', when:'ASAP', note:'Ronvid the Idiot challenges you to a fight.'},
  {id:'q23', name:'Event: Harassing a Troll', type:'Event', region:'Velen', from:'Wild Hunt', when:'ASAP', note:"North-West of the Inn at the crossroads, close to the river banks."},
  {id:'q24', name:"Races: Crow's Perch",   type:'Race',          region:'Velen',        from:'Wild Hunt', when:'ASAP', note:'Glitch can cause it to be impossible after Isle of Mists, but it resets after Something Ends, Something Begins. Still do it ASAP.'},
  {id:'q25', name:'Contract: Shrieker',    type:'Contract',      region:'Velen',        from:'Wild Hunt'},
  {id:'q26', name:'Event: Deadly Crossing I', type:'Event', region:'Velen', from:'Wild Hunt', when:'ASAP', note:'Bandits asking toll on troll bridge.'},
  {id:'q27', name:'Hunting a Witch',       type:'Main Quest',    region:'Velen',        from:'Wild Hunt'},
  {id:'q28', name:'The Dead Have No Defense', type:'Treasure Hunt', region:'Velen', from:'Wild Hunt', note:'South of Duen Hen.'},
  {id:'q29', name:"Don't Play with the Gods", type:'Treasure Hunt', region:'Velen', from:'Wild Hunt', note:'South-east of Duen Hen.'},
  {id:'q30', name:'Wandering in the Dark', type:'Main Quest',    region:'Velen',        from:'Wild Hunt', note:'From Keira.'},
  {id:'q31', name:'Magic Lamp',            type:'Side Quest',    region:'Velen',        from:'Wild Hunt', when:'Early in story', note:'Can be missed by refusing to help Keira at the end of "Wandering in the Dark".'},
  {id:'q32', name:'A Princess in Distress', type:'Main Quest',   region:'Velen',        from:'Wild Hunt'},
  {id:'q33', name:'Lynch Mob',             type:'Side Quest',    region:'Velen',        from:'Wild Hunt', when:'ASAP'},
  {id:'q34', name:'An Invitation from Keira Metz', type:'Side Quest', region:'Velen', from:'Wild Hunt', when:'Early in story', note:'Must be done before going to the Isle of Mists.'},
  {id:'q35', name:'A Towerful of Mice',    type:'Side Quest',    region:'Velen',        from:'Wild Hunt', when:'Early in story', note:'Must be done before going to the Isle of Mists.'},
  {id:'q36', name:'A Favor for a Friend',  type:'Side Quest',    region:'Velen',        from:'Wild Hunt', when:'Early in story', note:'Must be done before going to the Isle of Mists.'},
  {id:'q37', name:'For the Advancement of Learning', type:'Side Quest', region:'Velen', from:'Wild Hunt', when:'Early in story', note:'Must be done before going to the Isle of Mists.'},
  {id:'q38', name:'Sunken Chest',          type:'Treasure Hunt', region:'Velen',        from:'Wild Hunt', note:'South of Fyke Isle.'},
  {id:'q39', name:'A Dog\'s Life',         type:'Side Quest',    region:'Velen',        from:'Wild Hunt', when:'ASAP', note:'Follow the road east of Oreton — eventually you reach a pack of wolves attacking a stray dog.'},
  {id:'q40', name:"Event: Deadly Crossing IV / Highwayman's Cache", type:'Event', region:'Velen', from:'Wild Hunt', when:'ASAP', note:"East of Boatmaker's Hut."},
  {id:'q41', name:'Event: Highway Robbery', type:'Event', region:'Velen', from:'Wild Hunt', when:'ASAP', note:"Forested path from Boatmaker's Hut to the southwest — a 'trader' is being attacked by three bandits."},
  {id:'q42', name:'Event: Looters (II) – Ghoulish Gatherers', type:'Event', region:'Velen', from:'Wild Hunt', when:'ASAP', note:"Find them at the inactive Codger's Quarry."},
  {id:'q43', name:'Death by Fire',         type:'Side Quest',    region:'Velen',        from:'Wild Hunt', when:'ASAP', note:"West of Codgers' Quarry."},
  {id:'q44', name:'Fake Papers',           type:'Side Quest',    region:'Velen',        from:'Wild Hunt', when:'See Comment', note:'Do not complete before "Thou Shalt Not Pass".'},
  {id:'q45', name:'Thou Shalt Not Pass',   type:'Side Quest',    region:'Velen',        from:'Wild Hunt', when:'See Comment', note:"Start it before completing \"Fake Papers\" or before you talk to the baron after you visited the fisherman's hut."},
  {id:'q46', name:'Bitter Harvest',        type:'Side Quest',    region:'Velen',        from:'Wild Hunt', when:'ASAP', note:"North-West of Hanged Man's Tree."},
  {id:'q47', name:'The Volunteer',         type:'Side Quest',    region:'Velen',        from:'Wild Hunt'},
  {id:'q48', name:'Funeral Pyres',         type:'Side Quest',    region:'Velen',        from:'Wild Hunt', note:'West of Mulbrydale, next to a shrine.'},
  {id:'q49', name:"Event: A Man's Best Friend", type:'Event', region:'Velen', from:'Wild Hunt', when:'ASAP', note:"North-west of Hanged Man's Tree — remote farm."},
  {id:'q50', name:'Event: Follow-up — At the Mercy of Strangers II', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'ASAP', note:'Follow-up of a choice you made: if you saved John Verdun he returns offering payment.'},
  {id:'q51', name:'The Things Men Do For Coin...', type:'Treasure Hunt', region:'Novigrad', from:'Wild Hunt', note:'Island west of the Border Post.'},
  {id:'q52', name:'Event: Looters (I) – Revolting Peasants', type:'Event', region:'Velen', from:'Wild Hunt', when:'ASAP', note:'Woodland Gang on the wooded path east of Heatherton. Five infantry, three horsemen.'},
  {id:'q53', name:'Wild at Heart',         type:'Side Quest',    region:'Velen',        from:'Wild Hunt'},
  {id:'q54', name:"Contract: Jenny o' the Woods", type:'Contract', region:'Velen', from:'Wild Hunt'},
  {id:'q55', name:'Hazardous Goods',       type:'Side Quest',    region:'Velen',        from:'Wild Hunt', when:'ASAP'},
  {id:'q56', name:"Fool's Gold",           type:'Side Quest',    region:'Velen',        from:'Wild Hunt', when:'ASAP'},
  {id:'q57', name:'Out of the Frying Pan, into the Fire', type:'Treasure Hunt', region:'Velen', from:'Wild Hunt'},
  {id:'q58', name:'Hidden from the World', type:'Treasure Hunt', region:'Velen',        from:'Wild Hunt', note:'Across the water, southeast from Ferry Station signpost.'},
  {id:'q59', name:'Gwent: Velen Players',  type:'Side Quest',    region:'Velen',        from:'Wild Hunt', when:'ASAP', note:'Complete before Baron storyline ends in "Return to Crookback Bog", or before Isle of Mists.'},
  {id:'q60', name:'The Truth is in the Stars', type:'Side Quest', region:'Velen',       from:'Wild Hunt'},
  {id:'q61', name:'Event: Looters (III) – Toderas Bandits', type:'Event', region:'Velen', from:'Wild Hunt', when:'ASAP', note:'Village of Toderas — brief conversation turns violent.'},
  {id:'q62', name:'Fists of Fury: Velen',  type:'Side Quest',    region:'Velen',        from:'Wild Hunt'},
  {id:'q63', name:'Event: Caravan Attack', type:'Event', region:'Velen', from:'Wild Hunt', when:'ASAP', note:"Go to Marauder's Bridge then head west."},
  {id:'q64', name:'Tough Luck',            type:'Treasure Hunt', region:'Velen',        from:'Wild Hunt', note:"Question mark south east of Devil's Pit."},
  {id:'q65', name:'An Unfortunate Turn of Events', type:'Treasure Hunt', region:'Velen', from:'Wild Hunt', note:"Question mark south of Devil's Pit."},
  {id:'q66', name:'Blood Gold',            type:'Treasure Hunt', region:'Velen',        from:'Wild Hunt', note:'North-West of White Eagle Fort.'},
  {id:'q67', name:'Dowry',                 type:'Treasure Hunt', region:'Velen',        from:'Wild Hunt', note:'Question mark north of White Eagle Fort.'},
  {id:'q68', name:'Battlefield Loot',      type:'Treasure Hunt', region:'Velen',        from:'Wild Hunt', note:'North-West of White Eagle Fort.'},
  {id:'q69', name:'Ghosts of the Past',    type:'Side Quest',    region:'Velen',        from:'Wild Hunt', when:'Early in story', note:'You must simulate Witcher 2 choices and tell Voorhis you spared Letho — complete before going to Isle of Mists.'},
  {id:'q70', name:'The Fall of the House of Reardon', type:'Side Quest', region:'Velen', from:'Wild Hunt', note:'Receive from the woman next to the Notice Board.'},
  {id:'q71', name:"Forefathers' Eve",      type:'Side Quest',    region:'Velen',        from:'Wild Hunt', note:"Meet the Pellar in his house after completing \"A Towerful of Mice\", or he'll come to Crow's Perch during Family Matters."},
  {id:'q72', name:'Contract: Swamp Thing', type:'Contract',      region:'Velen',        from:'Wild Hunt'},
  {id:'q73', name:'Contract: The Merry Widow', type:'Contract', region:'Velen',         from:'Wild Hunt', note:'Needed for Witcher Wannabe.'},
  {id:'q74', name:"Event: Follow-up — On Death's Bed", type:'Event', region:'Velen', from:'Wild Hunt', when:'See Comment', note:"Follow-up of \"On Death's Bed\" — a guy near the Nilfgaardian camp tells you the outcome."},
  {id:'q75', name:'Blood Ties',            type:'Side Quest',    region:'Velen',        from:'Wild Hunt'},
  {id:'q76', name:'Contract: Patrol Gone Missing', type:'Contract', region:'Velen',     from:'Wild Hunt'},
  {id:'q77', name:'Scavenger Hunt: Griffin School Gear Upgrade Diagrams – Part 2', type:'Treasure Hunt', region:'Velen', from:'Wild Hunt', note:'"Edwin Greloff\'s First Map" sold by Armourer in Midcopse.'},
  {id:'q78', name:'Scavenger Hunt: Cat School Gear Upgrade Diagrams – Part 2', type:'Treasure Hunt', region:'Velen', from:'Wild Hunt', note:'Vendor and blacksmith in Blackbough.'},
  {id:'q79', name:'A Costly Mistake',      type:'Treasure Hunt', region:'Velen',        from:'Wild Hunt', note:"West of Hangman's Alley."},
  {id:'q80', name:"Queen Zuleyka's Treasure", type:'Treasure Hunt', region:'Velen',    from:'Wild Hunt', note:'Somewhat north of Coast of Wrecks — take the letter from the bed near the fireplace.'},
  {id:'q81', name:'Defender of the Faith', type:'Side Quest',    region:'Velen',        from:'Wild Hunt'},
  {id:'q82', name:'Event: Deadly Crossing III – Crookback Bog', type:'Event', region:'Velen', from:'Wild Hunt', when:'ASAP', note:"West of the Dragonslayer's Grotto."},
  {id:'q83', name:'The Whispering Hillock', type:'Side Quest',   region:'Velen',        from:'Wild Hunt', note:'If you don\'t trigger the quest first, you\'ll be forced there during "Ladies of the Wood".'},
  {id:'q84', name:"Ciri's Story: Fleeing the Bog", type:'Main Quest', region:'Velen',   from:'Wild Hunt'},
  {id:'q85', name:'Ladies of the Wood',    type:'Main Quest',    region:'Velen',        from:'Wild Hunt'},
  {id:'q86', name:'Contract: Woodland Beast', type:'Contract',   region:'Velen',        from:'Wild Hunt'},
  {id:'q87', name:'Sunken Treasure',       type:'Treasure Hunt', region:'Velen',        from:'Wild Hunt', note:"North-West of Hangman's Alley."},
  {id:'q88', name:'Scavenger Hunt: Griffin School Gear Upgrade Diagrams – Part 1', type:'Treasure Hunt', region:'Velen', from:'Wild Hunt', note:'"Edwin Greloff\'s First Map" sold by Armourer in Midcopse.'},
  {id:'q89', name:'Last Rites',            type:'Side Quest',    region:'Velen',        from:'Wild Hunt', note:'North of Blackbough — only available at night.'},

  // ── NOVIGRAD EARLY ─────────────────────────────────────────────────
  {id:'q90', name:'Event: Face Me if You Dare! II', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'ASAP', note:"Standing near the boat south-east of Novigrad."},
  {id:'q91', name:'Event: The Flame of Hatred', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'ASAP', note:'East of Hierarch Square — a preacher starts insulting you.'},
  {id:'q92', name:'Pyres of Novigrad',     type:'Main Quest',    region:'Novigrad',     from:'Wild Hunt', note:"GET THE ROSE OF REMEMBRANCE FROM TRISS' HOUSE! South of Hierarch Square."},
  {id:'q93', name:'Novigrad Dreaming',     type:'Main Quest',    region:'Novigrad',     from:'Wild Hunt', note:'South-east of Hierarch Square.'},
  {id:'q94', name:'Gwent: Playing Innkeeps', type:'Side Quest',  region:'Novigrad',     from:'Wild Hunt', when:'ASAP', note:'Start with Innkeeper Stjepan in The Alchemy Inn, Oxenfurt. Complete before Olivier dies in "Now or Never".'},
  {id:'q95', name:'Message from an Old Friend', type:'Side Quest', region:'Novigrad',   from:'Wild Hunt', note:'Find the book in the bookstore.'},
  {id:'q96', name:'A Walk on the Waterfront', type:'Side Quest', region:'Novigrad',     from:'Wild Hunt', when:'ASAP'},
  {id:'q97', name:'Warehouse of Woe',      type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'ASAP', note:'West of Novigrad Docks.'},
  {id:'q98', name:'Event: Strumpet In Distress', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'ASAP', note:'Argument behind first house on the docks.'},
  {id:'q99', name:'Event: Suspicious Shakedown', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'ASAP', note:'South of the Gate of the Hierarch near the canal.'},
  {id:'q100',name:'Event: Drunken Rabble', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'ASAP', note:'Close to or exiting the Golden Sturgeon.'},
  {id:'q101',name:'Event: Face Me if You Dare! III', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'ASAP', note:"West of Hierarch Square. Meditate a few days if you did the last part recently."},
  {id:'q102',name:"Hey, You Wanna Look at My Stuff?", type:'Side Quest', region:'Novigrad', from:'Wild Hunt', note:"Talk to halfling merchant south-west of St. Gregory's Bridge."},
  {id:'q103',name:'Scavenger Hunt: Griffin School Gear', type:'Treasure Hunt', region:'Novigrad', from:'Wild Hunt', note:'Given to you automatically once you find a related piece.'},
  {id:'q104',name:'Broken Flowers',        type:'Main Quest',    region:'Novigrad',     from:'Wild Hunt', note:"ACCEPT ROSA'S LESSON REQUEST! Go to inn to meet Dandelion after \"Novigrad Dreaming\"."},
  {id:'q105',name:'Event: Never Trust Children', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'ASAP', note:"Outside the Crooked House in The Bits, northeast of Hierarch Square."},
  {id:'q106',name:'Hidden Messages of the Nilfgaardian Kind', type:'Side Quest', region:'Novigrad', from:'Wild Hunt', when:'See Comment', note:'Do this quick if you want to see the full start of the quest.'},
  {id:'q107',name:'The Gangs of Novigrad', type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'Early in story', note:'Meet Cleaver west of Hierarch Square after "Get Junior" quest is triggered. Can still be failed.'},
  {id:'q108',name:'Honor Among Thieves',   type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'See Comment', note:'You must let Rico go during "Get Junior" main quest to trigger this, then talk to the Beggar King.'},
  {id:'q109',name:'Event: Eternal Flame Interrogation', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'ASAP', note:'Northwest of Southern Gate Novigrad — get stopped for questioning by 2 "guards".'},
  {id:'q110',name:"Event: Scoia'tael Ambush", type:'Event', region:'Novigrad', from:'Wild Hunt', when:'See Comment', note:'Follow-up: if you told the contract issuer the truth about "Woodland Beast", Vernossiel will try to ambush you later.'},
  {id:'q111',name:"Count Reuven's Treasure", type:'Main Quest', region:'Novigrad',     from:'Wild Hunt', note:'Available after "Broken Flowers". Talk to Sigi Reuven in the Bathhouse.'},
  {id:'q112',name:'The Nobleman Statuette', type:'Side Quest',   region:'Novigrad',     from:'Wild Hunt', when:'Early in story', note:'Bought from a merchant — before Triss is gone (before "Now or Never").'},
  {id:'q113',name:'The Dwarven Document Dilemma', type:'Side Quest', region:'Novigrad', from:'Wild Hunt'},
  {id:'q114',name:'Haunted House',         type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', note:'Find message on noticeboard after completing "Novigrad Dreaming".'},
  {id:'q115',name:'Fencing Lessons',       type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'See Comment', note:"You must accept Rosa's lesson offer during \"Broken Flowers\"."},
  {id:'q116',name:'Contract: An Elusive Thief', type:'Contract', region:'Novigrad',    from:'Wild Hunt'},
  {id:'q117',name:'Gwent: Big City Players', type:'Side Quest',  region:'Novigrad',     from:'Wild Hunt', when:'ASAP BUT', note:'Notice board near the docks — do not play Serenity before unlocking Dijkstra, and complete it while he\'s available.'},
  {id:'q118',name:'Fists of Fury: Novigrad', type:'Side Quest',  region:'Novigrad',     from:'Wild Hunt'},
  {id:'q119',name:'A Feast for Crows',     type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'See Comment', note:'Should appear somewhat late in game.'},
  {id:'q120',name:'Event: The Most Truest of Basilisks', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'ASAP', note:'Northeast of Oxenfurt Harbor near the bridge — a guy entertaining guards with a caged Basilisk.'},
  {id:'q121',name:"Ciri's Story: Visiting Junior", type:'Main Quest', region:'Novigrad', from:'Wild Hunt'},
  {id:'q122',name:'Witcher Wannabe',       type:'Side Quest',    region:'Velen',        from:'Wild Hunt', note:'Should appear somewhat late in game.'},
  {id:'q123',name:'Get Junior',            type:'Main Quest',    region:'Novigrad',     from:'Wild Hunt', note:'Available after "Broken Flowers". Talk to Sigi Reuven in the Bathhouse.'},
  {id:'q124',name:'A Favor for Radovid',   type:'Main Quest',    region:'Novigrad',     from:'Wild Hunt'},
  {id:'q125',name:"The Play's the Thing",  type:'Main Quest',    region:'Novigrad',     from:'Wild Hunt'},
  {id:'q126',name:"Ciri's Story: Breakneck Speed", type:'Main Quest', region:'Novigrad', from:'Wild Hunt', note:"You can get Ciri's sword, Zireael, during this. Watch a tutorial to find out how."},
  {id:'q127',name:'A Poet Under Pressure', type:'Main Quest',    region:'Novigrad',     from:'Wild Hunt', note:"When you get the painting, put it in your stash. Then give it to Dandelion — it will stay in your stash and you can put it up at Corvo Bianco."},
  {id:'q128',name:'Event: Witch Hunter Raids I', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'ASAP', note:'No exclamation mark! Secondary quest in the Farcorners slums.'},
  {id:'q129',name:'Empty Coop',            type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'ASAP', note:'East of Honeyfill Meadworks.'},
  {id:'q130',name:'Event: A Warm Welcome', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'ASAP', note:'South west of Wheat Fields.'},
  {id:'q131',name:'Event: Strangers in the Night', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'ASAP', note:'West from Carsten — merchant vs Nilfgaardian soldier.'},
  {id:'q132',name:'Event: Pest Man Wish',  type:'Event', region:'Velen', from:'Wild Hunt', when:'ASAP', note:'Sequel to "Hazardous Goods" — east of Reardon Manor.'},
  {id:'q133',name:'Event: Karmic Justice', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'ASAP', note:'Can be started by traveling at night between Southern and Tretogor Gates.'},
  {id:'q134',name:'A Barnful of Trouble',  type:'Side Quest',    region:'Velen',        from:'Wild Hunt', when:'ASAP'},
  {id:'q135',name:'Event: Racists of Novigrad (I) – Female Elf', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'ASAP', note:"North of Portside Gate."},
  {id:'q136',name:'Event: Racists of Novigrad (II) – Male Elf', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'ASAP', note:'Southeast of Tretogor Gate.'},
  {id:'q137',name:"Love's Cruel Snares",   type:'Side Quest',    region:'Velen',        from:'Wild Hunt', when:'See Comment', note:'Should appear somewhat late in game.'},
  {id:'q138',name:'A Plea Ignored',        type:'Treasure Hunt', region:'Velen',        from:'Wild Hunt', note:'South of Condyle.'},
  {id:'q139',name:'Contract: The Mystery of the Byways Murders', type:'Contract', region:'Velen', from:'Wild Hunt'},
  {id:'q140',name:'Race: The Great Erasmus Vegelbud Memorial Derby', type:'Race', region:'Novigrad', from:'Wild Hunt'},
  {id:'q141',name:'An Eye for an Eye',     type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'Early in story', note:'Must be done before going to Isle of Mists.'},
  {id:'q142',name:'Of Diary and Darkness', type:'Side Quest',    region:'Velen',        from:'Wild Hunt', note:'Merchant sells some quest items.'},
  {id:'q143',name:'A Dangerous Game',      type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'Early in story', note:'Make sure to collect the green statuette or you will not be able to complete "The Soldier Statuette".'},
  {id:'q144',name:'A Tome Entombed',       type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', note:'Entrance to sewers halfway between Hierarch Square and Oxenfurt Gate signposts.'},
  {id:'q145',name:'The Soldier Statuette', type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'Early in story', note:'Found during "A Dangerous Game" — must be completed before "Now or Never".'},
  {id:'q146',name:"Redania's Most Wanted", type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'Early in story'},
  {id:'q147',name:'Cabaret',               type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'Early in story', note:'Must be done before Isle of Mists — talk to Dandelion after "A Poet Under Pressure".'},
  {id:'q148',name:'Carnal Sins',           type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'Early in story', note:'Must be done before going to the Isle of Mists.'},
  {id:'q149',name:'A Matter of Life and Death', type:'Side Quest', region:'Novigrad',   from:'Wild Hunt', when:'Early in story', note:"The quest starts where Triss holds shelter."},
  {id:'q150',name:'Event: Witch Hunter Raids II', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'ASAP', note:'Available after A Matter of Life or Death. No exclamation mark! Near Gildorf Square.'},
  {id:'q151',name:'Novigrad Hospitality',  type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', note:'Follow the road leading north-west.'},
  {id:'q152',name:'Event: Novigrad Lockdown', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'ASAP', note:'Becomes available after "A Matter of Life and Death".'},
  {id:'q153',name:'Novigrad, Closed City II', type:'Side Quest', region:'Novigrad',     from:'Wild Hunt', when:'See Comment', note:'Becomes available after "A Matter of Life and Death".'},
  {id:'q154',name:'Novigrad, Closed City',  type:'Side Quest',   region:'Novigrad',     from:'Wild Hunt', when:'See Comment', note:'Becomes available after "A Matter of Life and Death" — trigger by talking to Lussi.'},
  {id:'q155',name:'Event: Saving Moritz Diefenthal from the Pyre', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'See Comment', note:'Available after A Matter of Life or Death, before "Now or Never". No exclamation mark!'},
  {id:'q156',name:'Spooked Mare',          type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', note:'Between Crossroads and Novigrad Gate.'},
  {id:'q157',name:'Contract: Deadly Delights', type:'Contract',  region:'Novigrad',     from:'Wild Hunt', when:'ASAP', note:'Notice board at the docks.'},
  {id:'q158',name:'Out on Your Arse!',      type:'Side Quest',   region:'Novigrad',     from:'Wild Hunt', when:'ASAP BUT', note:"Becomes available after Contract: Deadly Delights — north of Portside Gate in Crippled Kate's Brothel."},
  {id:'q159',name:'Contract: The White Lady', type:'Contract',   region:'Novigrad',     from:'Wild Hunt'},

  // ── DESTINATION SKELLIGE ───────────────────────────────────────────
  {id:'q160',name:'Destination: Skellige', type:'Main Quest',    region:'Novigrad',     from:'Wild Hunt'},
  {id:'q161',name:'The King is Dead – Long Live the King', type:'Main Quest', region:'Skellige', from:'Wild Hunt'},
  {id:'q162',name:'Crime and Punishment',  type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', when:'ASAP', note:'Sail the coast to the east — be sure to visit Rogne afterwards.'},
  {id:'q163',name:"Event: Yorg's Sister",  type:'Event',         region:'Skellige',     from:'Wild Hunt', when:'See Comment', note:'Follow-up to "Crime and Punishment" — go to Rogne to see a group discussing Yorg.'},
  {id:'q164',name:'Finders Keepers',       type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', when:'ASAP', note:"Small island northeast of Giant's Toes. This quest disappears if you don't do it after clearing the area of pirates."},
  {id:'q165',name:'Event: Farting Trolls', type:'Event',         region:'Skellige',     from:'Wild Hunt', when:'ASAP', note:'Southeast of Wild Shore.'},
  {id:'q166',name:'Brave Fools Die Young', type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', when:'ASAP', note:'Follow the road out of Fyresdal to the north — large flaming monument.'},
  {id:'q167',name:'Event: Woe is Me (Palisade ambush)', type:'Event', region:'Skellige', from:'Wild Hunt', when:'ASAP', note:'ENTER FROM THE WEST! Talk to peasant near the travel sign.'},
  {id:'q168',name:'Worthy of Trust',       type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', note:"Meet him twice near Kaer Trolde harbor, then go to Fyresdal for the last time."},
  {id:'q169',name:'The Family Blade',      type:'Side Quest',    region:'Skellige',     from:'Wild Hunt'},
  {id:'q170',name:'Event: The Four Faces of Hemdall', type:'Event', region:'Skellige', from:'Wild Hunt', when:'ASAP', note:'Northwest of Trottheim — three pirates and a pilgrim.'},
  {id:'q171',name:'Flesh for Sale',        type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', when:'See Comment', note:'Complete before starting "Following the Thread".'},
  {id:'q172',name:'The Price of Honor',    type:'Side Quest',    region:'Skellige',     from:'Wild Hunt'},
  {id:'q173',name:"Ironsides' Treasure",   type:'Treasure Hunt', region:'Skellige',     from:'Wild Hunt', note:'Question mark on biggest island north of Faroe Isle (Harviken).'},
  {id:'q174',name:"Event: Siren's Call",   type:'Event',         region:'Skellige',     from:'Wild Hunt', when:'ASAP', note:'East from Arinbjorn.'},
  {id:'q175',name:'Event: Never Trust Children II – Skellige', type:'Event', region:'Skellige', from:'Wild Hunt', when:'ASAP', note:'Path from Sund to Arinbjorn.'},
  {id:'q176',name:'Event: Call of the Wild', type:'Event',       region:'Skellige',     from:'Wild Hunt', when:'ASAP', note:'East from Arinbjorn — sounds of wolves in the forest to the south.'},
  {id:'q177',name:'Contract: The Phantom of Eldberg', type:'Contract', region:'Skellige', from:'Wild Hunt', when:'ASAP'},
  {id:'q178',name:'Stranger in a Strange Land', type:'Side Quest', region:'Skellige',   from:'Wild Hunt', when:'ASAP', note:"Don't use Axii on the guard — get help from Simun."},
  {id:'q179',name:'The Cave of Dreams',    type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', when:'ASAP', note:"South-East of Holmstein's Port on shore."},
  {id:'q180',name:'An Unpaid Debt',        type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', when:'ASAP', note:"Available if you've completed \"Stranger in a Strange Land\" and used Simun to escape."},
  {id:'q181',name:'Armed Assault',         type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', when:'ASAP', note:'Tied to Mad Lugos — do it before Possession + The Lord of Undvik completion. Meditate at the cottage if nothing happens.'},
  {id:'q182',name:'Hard Times',            type:'Side Quest',    region:'Skellige',     from:'Wild Hunt'},
  {id:'q183',name:'Echoes of the Past',    type:'Main Quest',    region:'Skellige',     from:'Wild Hunt'},
  {id:'q184',name:'Shock Therapy',         type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', note:'Talk to one of the druids.'},
  {id:'q185',name:'Practicum in Advanced Alchemy', type:'Side Quest', region:'Skellige', from:'Wild Hunt', when:'ASAP', note:'Talk to Gremist outside his home or to the herbalist east of Oxenfurt.'},
  {id:'q186',name:'Gwent: Skellige Style', type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', when:'Early in story', note:"You need to have completed Gwent in Velen and at least started Gwent: Big City Players. Make sure to play with Lugos while he's available."},
  {id:'q187',name:'Iron Maiden',           type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', note:'East of Harviken.'},
  {id:'q188',name:'Hidden in the Depths',  type:'Treasure Hunt', region:'Skellige',     from:'Wild Hunt', when:'See Comment', note:"Question mark south west of Harviken. The quest auto-completes — you have to dive into the cave to find the loot."},
  {id:'q189',name:'A Hallowed Horn',       type:'Side Quest',    region:'Skellige',     from:'Wild Hunt'},
  {id:'q190',name:'The Nithing',           type:'Side Quest',    region:'Skellige',     from:'Wild Hunt'},
  {id:'q191',name:"The Heroes' Pursuits: Kaer Trolde", type:'Race', region:'Skellige',  from:'Wild Hunt'},
  {id:'q192',name:"The Heroes' Pursuits: Fayrlund", type:'Race', region:'Skellige',     from:'Wild Hunt', note:'North-east of Fayrlund.'},
  {id:'q193',name:'The Lord of Undvik',    type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', when:'Early in story', note:'Must be done before going to Isle of Mists.'},
  {id:'q194',name:'Precious Haul',         type:'Treasure Hunt', region:'Skellige',     from:'Wild Hunt', note:'North of Abandoned Village, on the shore.'},
  {id:'q195',name:'Shortcut',              type:'Treasure Hunt', region:'Skellige',     from:'Wild Hunt', note:'North side of the small lake.'},
  {id:'q196',name:'Possession',            type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', when:'Early in story', note:'Must be done before sailing off for the Sunstone.'},
  {id:'q197',name:'Not Only Eagles Dare',  type:'Treasure Hunt', region:'Skellige',     from:'Wild Hunt', note:'Find the wreck south-east of Svorlag.'},
  {id:'q198',name:'Master of the Arena',   type:'Side Quest',    region:'Skellige',     from:'Wild Hunt'},
  {id:'q199',name:'Family Fortune',        type:'Treasure Hunt', region:'Skellige',     from:'Wild Hunt'},
  {id:'q200',name:'For Fame and Glory',    type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', note:'West, just outside Larvik.'},
  {id:'q201',name:'Missing Persons',       type:'Main Quest',    region:'Skellige',     from:'Wild Hunt'},
  {id:'q202',name:'The Calm Before the Storm', type:'Main Quest', region:'Skellige',    from:'Wild Hunt'},
  {id:'q203',name:'Nameless',              type:'Main Quest',    region:'Skellige',     from:'Wild Hunt'},
  {id:'q204',name:'A Mysterious Passenger', type:'Main Quest',   region:'Skellige',     from:'Wild Hunt'},
  {id:'q205',name:'The Last Wish',         type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', when:'Early in story', note:'Must be done before going to Isle of Mists.'},
  {id:'q206',name:"In Wolf's Clothing",    type:'Side Quest',    region:'Skellige',     from:'Wild Hunt'},
  {id:'q207',name:'Contract: Strange Beast', type:'Contract',    region:'Skellige',     from:'Wild Hunt'},
  {id:'q208',name:"King's Gambit",         type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', when:'Early in story', note:'Cerys is best choice for both the story and to get the Place of Power. Must be done before Isle of Mists.'},
  {id:'q209',name:'Coronation',            type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', when:'Early in story', note:'Must be done before Isle of Mists.'},
  {id:'q210',name:'Fists of Fury: Skellige', type:'Side Quest',  region:'Skellige',     from:'Wild Hunt'},
  {id:'q211',name:"Contract: Muire D'yaeblen", type:'Contract',  region:'Skellige',     from:'Wild Hunt'},
  {id:'q212',name:'Fists of Fury: Champion of Champions', type:'Side Quest', region:'Skellige', from:'Wild Hunt'},
  {id:'q213',name:'The Tower Outta Nowheres', type:'Side Quest', region:'Skellige',     from:'Wild Hunt'},
  {id:'q214',name:'The Path of Warriors',  type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', note:'Comes available after "The Tower Outta Nowheres".'},
  {id:'q215',name:'Nilfgaardian Treasure', type:'Treasure Hunt', region:'Skellige',     from:'Wild Hunt'},
  {id:'q216',name:'Contract: Here Comes the Groom', type:'Contract', region:'Skellige', from:'Wild Hunt'},
  {id:'q217',name:'Event: Yustianna Disturbed', type:'Event', region:'Skellige', from:'Wild Hunt', when:'ASAP', note:'You need the Eye of Nehaleni if you want to loot without bandits noticing.'},
  {id:'q218',name:'Scavenger Hunt: Bear School Gear', type:'Treasure Hunt', region:'Skellige', from:'Wild Hunt', note:'Given to you automatically once you find a related piece.'},
  {id:'q219',name:'Freya Be Praised!',     type:'Treasure Hunt', region:'Skellige',     from:'Wild Hunt', note:'East side of the lake right under Blandare.'},
  {id:'q220',name:'X Marks the Spot',      type:'Treasure Hunt', region:'Skellige',     from:'Wild Hunt', note:'South-east of Blandare.'},
  {id:'q221',name:'Contract: Missing Miners', type:'Contract',   region:'Skellige',     from:'Wild Hunt'},
  {id:'q222',name:'The Sad Tale of the Grossbart Brothers', type:'Side Quest', region:'Skellige', from:'Wild Hunt'},
  {id:'q223',name:'Scavenger Hunt: Bear School Gear Upgrade Diagrams – Part 1', type:'Treasure Hunt', region:'Skellige', from:'Wild Hunt', note:'"Ibraham Savi\'s First Map" sold by Blacksmith in Oxenfurt.'},
  {id:'q224',name:'Scavenger Hunt: Bear School Gear Upgrade Diagrams – Part 2', type:'Treasure Hunt', region:'Skellige', from:'Wild Hunt', note:'Map sold by Blacksmith near Bridge to Kaer Trolde.'},
  {id:'q225',name:'Scavenger Hunt: Griffin School Gear Upgrade Diagrams – Part 3', type:'Treasure Hunt', region:'Novigrad', from:'Wild Hunt', note:'Map sold by Armorer near Hierarch Square, Novigrad.'},
  {id:'q226',name:'Taken as a Lass',       type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', when:'See Comment', note:"Along the shore between Redgill and Grotto. Don't talk to Kurisu in Freya's temple on Hindarsfjall before starting this quest."},
  {id:'q227',name:'Scavenger Hunt: Wolf School Gear Upgrade Diagrams – Part 6', type:'Treasure Hunt', region:'Skellige', from:'Wild Hunt', note:'Map sold by Armorer near Bridge to Kaer Trolde.'},
  {id:'q228',name:'Inheritance',           type:'Treasure Hunt', region:'Skellige',     from:'Wild Hunt'},
  {id:'q229',name:'Contract: Missing Son', type:'Contract',      region:'Skellige',     from:'Wild Hunt', note:'Talk to man on crossroads.'},
  {id:'q230',name:'Peace Disturbed',       type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', note:'Cave north of Crossroads travel point.'},
  {id:'q231',name:'In the Heart of the Woods', type:'Contract',  region:'Skellige',     from:'Wild Hunt'},
  {id:'q232',name:"A Bard's Beloved",      type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', note:'Talk to Bard in cave east of Palisade.'},
  {id:'q233',name:'Free Spirit',           type:'Side Quest',    region:'Skellige',     from:'Wild Hunt', when:'ASAP', note:'On the coast of big island right before the Ancient Crypt signpost.'},
  {id:'q234',name:"Unlucky's Treasure",    type:'Treasure Hunt', region:'Skellige',     from:'Wild Hunt', note:"Question mark on island where guy from the \"Free Spirit\" quest lives."},
  {id:'q235',name:'Abandoned Sawmill',     type:'Side Quest',    region:'Skellige',     from:'Wild Hunt'},
  {id:'q236',name:'From a Land Far, Far Away', type:'Side Quest', region:'Skellige',    from:'Wild Hunt', note:"East of Redgill — small island called Hemdall's Finger."},
  {id:'q237',name:'Coast of Wrecks',       type:'Treasure Hunt', region:'Novigrad',     from:'Wild Hunt', note:'Island group west of Ursten.'},
  {id:'q238',name:'Scavenger Hunt: Griffin School Gear Upgrade Diagrams – Part 4', type:'Treasure Hunt', region:'Novigrad', from:'Wild Hunt', note:'Map sold by Hattori the master blacksmith, Novigrad.'},
  {id:'q239',name:'Contract: The Griffin from the Highlands', type:'Contract', region:'Velen', from:'Wild Hunt'},
  {id:'q240',name:'Master Armorers',       type:'Side Quest',    region:'Multiple',     from:'Wild Hunt'},

  // ── MORE VELEN & NOVIGRAD ──────────────────────────────────────────
  {id:'q241',name:'Contract: Mysterious Tracks', type:'Contract', region:'Velen',       from:'Wild Hunt'},
  {id:'q242',name:'Contract: Missing Brother', type:'Contract',   region:'Velen',       from:'Wild Hunt'},
  {id:'q243',name:'Black Pearl',           type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', note:'Right outside the Golden Sturgeon in Harborside — man named Nidas.'},
  {id:'q244',name:'Gwent: Old Pals',       type:'Side Quest',    region:'Multiple',     from:'Wild Hunt', when:'Early in story', note:'Best to start this quest by playing Zoltan.'},
  {id:'q245',name:'Following the Thread',  type:'Side Quest',    region:'Multiple',     from:'Wild Hunt', when:'Early in story BUT', note:'Do NOT start before completing "Flesh for Sale". If you talk to Lambert first, you won\'t be able to play "Flesh for Sale".'},
  {id:'q246',name:'Now or Never',          type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'Early in story', note:"Must be done before Isle of Mists — complete Gwent: Playing Innkeeps before starting this quest."},
  {id:'q247',name:'A Deadly Plot',         type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'Early in story', note:'PLAY VERNON AT GWENT BEFORE THIS! You must accept Dijkstra\'s offer at end of "Now or Never" to start this quest.'},
  {id:'q248',name:'Gwent: Playing Thaler', type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'Early in story', note:"After helping Thaler with the trolls during \"A Deadly Plot\", talk to him. If not, find him in the Seven Cats Inn."},
  {id:'q249',name:"Collect 'Em All",       type:'Side Quest',    region:'Multiple',     from:'Wild Hunt'},
  {id:'q250',name:'High Stakes',           type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', note:'Find the notice at the noticeboard near St. Gregor\'s Bridge. Play with opponents soon enough to avoid failed objectives.'},

  // ── CIRI STORIES & FAMILY MATTERS ─────────────────────────────────
  {id:'q251',name:"Ciri's Story: The Race", type:'Main Quest',   region:'Velen',        from:'Wild Hunt'},
  {id:'q252',name:"Ciri's Story: Out of the Shadows", type:'Main Quest', region:'Velen', from:'Wild Hunt'},
  {id:'q253',name:'Family Matters',        type:'Main Quest',    region:'Velen',        from:'Wild Hunt', note:'Do not do this during Velen. Wait until "A Mysterious Stranger" quest is finished.'},
  {id:'q254',name:"In Ciri's Footsteps",   type:'Main Quest',    region:'Multiple',     from:'Wild Hunt'},
  {id:'q255',name:'Return to the Crookback Bog', type:'Side Quest', region:'Velen',     from:'Wild Hunt', when:'Early in story', note:'Must be done before Ugly Baby.'},
  {id:'q256',name:"Event: Saving Farmer's Daughter from Soldiers", type:'Event', region:'Velen', from:'Wild Hunt', when:'ASAP', note:'A farmer is begging a soldier not to be killed.'},
  {id:'q257',name:"Event: Saving Farmer's Daughter from Soldiers II", type:'Event', region:'Velen', from:'Wild Hunt', when:'ASAP', note:'A farmer is begging a soldier to leave his daughter alone.'},
  {id:'q258',name:'Event: Deadly Crossing II – Mulbrydale', type:'Event', region:'Velen', from:'Wild Hunt', when:'ASAP BUT', note:'If soldiers are still there, fast travel to Vizima and back. Looters should now be there.'},

  // ── SKELLIGE (more) ────────────────────────────────────────────────
  {id:'q259',name:"The Heroes' Pursuits: Fyresdal", type:'Race', region:'Skellige',     from:'Wild Hunt'},
  {id:'q260',name:'Contract: Dragon',      type:'Contract',      region:'Skellige',     from:'Wild Hunt'},
  {id:'q261',name:"Contract: Skellige's Most Wanted", type:'Contract', region:'Skellige', from:'Wild Hunt'},
  {id:'q262',name:'Scavenger Hunt: Wolf School Gear Upgrade Diagrams – Part 3', type:'Treasure Hunt', region:'Skellige', from:'Wild Hunt', note:'Map sold by Armorer near Bridge to Kaer Trolde.'},
  {id:'q263',name:"The Heroes' Pursuits: For the Goddess' Glory!", type:'Race', region:'Skellige', from:'Wild Hunt', note:'Complete the other races in Skellige first.'},
  {id:'q264',name:'Ruins, Hidden Treasure, You Know', type:'Treasure Hunt', region:'Skellige', from:'Wild Hunt', note:'Corpse just east through the gate of Drove Ruins — NO QUESTION MARK!'},
  {id:'q265',name:'Pearls of the Coast',   type:'Treasure Hunt', region:'Skellige',     from:'Wild Hunt', note:'South of Eldberg Lighthouse.'},

  // ── KAER MORHEN ────────────────────────────────────────────────────
  {id:'q266',name:'The Bastion',           type:'Side Quest',    region:'Kaer Morhen',  from:'Wild Hunt', note:'Requires a magic lamp — complete "Magic Lamp" first.'},
  {id:'q267',name:'Scavenger Hunt: Wolf School Gear', type:'Treasure Hunt', region:'Kaer Morhen', from:'Wild Hunt', note:'Given to you automatically once you find a related piece.'},
  {id:'q268',name:'Scavenger Hunt: Wolf School Gear Upgrade Diagrams – Part 2', type:'Treasure Hunt', region:'Velen', from:'Wild Hunt', note:'Map sold by Blacksmith in Lindenvale.'},
  {id:'q269',name:'Monster Slayer',        type:'Side Quest',    region:'Kaer Morhen',  from:'Wild Hunt', note:'North-East of Lakeside Hut sign.'},
  {id:'q270',name:"The Witcher's Forge",   type:'Side Quest',    region:'Kaer Morhen',  from:'Wild Hunt', note:'Find a book behind stairs near the kitchen. You need Eye of Nehaleni from Keira Metz to complete.'},
  {id:'q271',name:'To Bait a Forktail...',  type:'Main Quest',   region:'Kaer Morhen',  from:'Wild Hunt', note:'Tied in to Ugly Baby.'},
  {id:'q272',name:"Berengar's Blade",      type:'Side Quest',    region:'Kaer Morhen',  from:'Wild Hunt', when:'ASAP', note:'As soon as you get to Kaer Morhen, search the lower area near the main gate for a crate.'},
  {id:'q273',name:'Scavenger Hunt: Wolf School Gear Upgrade Diagrams – Part 4', type:'Treasure Hunt', region:'Novigrad', from:'Wild Hunt', note:'Map sold by Armorer near Hierarch Square, Novigrad.'},
  {id:'q274',name:'Scavenger Hunt: Wolf School Gear Upgrade Diagrams – Part 5', type:'Treasure Hunt', region:'Novigrad', from:'Wild Hunt', note:'Map sold by Hattori the master blacksmith, Novigrad.'},
  {id:'q275',name:'Event: Trail of Echoes (Witcher Cave)', type:'Event', region:'Kaer Morhen', from:'Wild Hunt', when:'ASAP', note:'It is complete when you get 25 XP.'},
  {id:'q276',name:'Greenhouse Effect',     type:'Side Quest',    region:'Kaer Morhen',  from:'Wild Hunt', note:'From Iron Mine fast travel point head south, cross the water, past the cave — Greenhouse at the end of the path.'},
  {id:'q277',name:'The Final Trial',       type:'Main Quest',    region:'Kaer Morhen',  from:'Wild Hunt', note:'Tied in to Ugly Baby.'},
  {id:'q278',name:'Disturbance',           type:'Main Quest',    region:'Kaer Morhen',  from:'Wild Hunt', note:'Tied in to Ugly Baby.'},
  {id:'q279',name:'No Place Like Home',    type:'Main Quest',    region:'Kaer Morhen',  from:'Wild Hunt'},
  {id:'q280',name:'Va Fail, Elaine',       type:'Main Quest',    region:'Kaer Morhen',  from:'Wild Hunt'},
  {id:'q281',name:'Ugly Baby',             type:'Main Quest',    region:'Kaer Morhen',  from:'Wild Hunt', when:'Point of no return 1', note:"REMEMBER TO GET TRISS' EARRING!"},

  // ── NOVIGRAD (late) ────────────────────────────────────────────────
  {id:'q282',name:'Of Swords and Dumplings', type:'Side Quest',  region:'Novigrad',     from:'Wild Hunt'},
  {id:'q283',name:'Scavenger Hunt: Cat School Gear Upgrade Diagrams – Part 1', type:'Treasure Hunt', region:'Velen', from:'Wild Hunt', note:'Vendor and blacksmith in Blackbough, Velen.'},
  {id:'q284',name:'Scavenger Hunt: Cat School Gear Upgrade Diagrams – Part 3', type:'Treasure Hunt', region:'Velen', from:'Wild Hunt', note:'"Adalbert Kermith\'s Third Map" sold by Crow\'s Perch Vendor.'},
  {id:'q285',name:'Scavenger Hunt: Wolf School Gear Upgrade Diagrams – Part 1', type:'Treasure Hunt', region:'Novigrad', from:'Wild Hunt', note:'Map sold by Hattori the master blacksmith, Novigrad.'},
  {id:'q286',name:'Scavenger Hunt: Bear School Gear Upgrade Diagrams – Part 3', type:'Treasure Hunt', region:'Skellige', from:'Wild Hunt', note:'Blacksmith near Bridge to Kaer Trolde.'},
  {id:'q287',name:'Scavenger Hunt: Cat School Gear', type:'Treasure Hunt', region:'Novigrad', from:'Wild Hunt', note:"In a house close by the Portside Gate sign — find a diary on the desk which begins this quest."},
  {id:'q288',name:'Scavenger Hunt: Bear School Gear Upgrade Diagrams – Part 4', type:'Treasure Hunt', region:'Skellige', from:'Wild Hunt', note:'Map sold by Blacksmith near Bridge to Kaer Trolde.'},
  {id:'q289',name:'Scavenger Hunt: Cat School Gear Upgrade Diagrams – Part 4', type:'Treasure Hunt', region:'Velen', from:'Wild Hunt', note:'"Adalbert Kermith\'s Fourth Map" sold by Lindenvale Vendor.'},

  // ── DLC — CONTRACT & SIDE (base) ─────────────────────────────────
  {id:'q290',name:'Contract: The Beast of Honorton', type:'Contract', region:'Velen', from:'Wild Hunt', when:'ASAP', note:'DLC — initially listed as a witcher contract, then transforms into "Where the Cat and Wolf Play..."'},
  {id:'q291',name:'Where the Cat and Wolf Play...', type:'Side Quest', region:'Velen', from:'Wild Hunt', when:'See Comment', note:'Initially listed as Contract: The Beast of Honorton.'},
  {id:'q292',name:'Take What You Want',    type:'Side Quest',    region:'Velen',        from:'Wild Hunt', when:'ASAP', note:'Only available if you spare Gaetan.'},
  {id:'q293',name:'Contract: Doors Slamming Shut', type:'Contract', region:'Novigrad', from:'Wild Hunt'},
  {id:'q294',name:'Contract: Lord of the Wood', type:'Contract', region:'Novigrad',    from:'Wild Hunt'},
  {id:'q295',name:'Contract: The Apiarian Phantom', type:'Contract', region:'Novigrad', from:'Wild Hunt'},

  // ── BROTHERS IN ARMS / ISLE OF MISTS ──────────────────────────────
  {id:'q296',name:'Brothers in Arms: Velen', type:'Main Quest',  region:'Velen',        from:'Wild Hunt', note:'Will probably autocomplete.'},
  {id:'q297',name:'Brothers in Arms: Nilfgaard', type:'Main Quest', region:'Vizima',    from:'Wild Hunt'},
  {id:'q298',name:'Brothers in Arms: Novigrad', type:'Main Quest', region:'Novigrad',   from:'Wild Hunt'},
  {id:'q299',name:'Brothers in Arms: Skellige', type:'Main Quest', region:'Skellige',   from:'Wild Hunt'},
  {id:'q300',name:'The Isle of Mists',     type:'Main Quest',    region:'Multiple',     from:'Wild Hunt'},
  {id:'q301',name:'The Battle of Kaer Morhen', type:'Main Quest', region:'Kaer Morhen', from:'Wild Hunt'},
  {id:'q302',name:'Blood on the Battlefield', type:'Main Quest', region:'Kaer Morhen',  from:'Wild Hunt'},
  {id:'q303',name:'Bald Mountain',         type:'Main Quest',    region:'Velen',        from:'Wild Hunt', note:'REMEMBER TO GET THE MAGIC ACORN!'},
  {id:'q304',name:'Contract: Phantom of the Trade Route', type:'Contract', region:'Velen', from:'Wild Hunt'},

  // ── ENDGAME NOVIGRAD ──────────────────────────────────────────────
  {id:'q305',name:'A Final Kindness',      type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'See Comment', note:"If Geralt allowed Keira to leave to bargain with Radovid, this quest triggers after Bald Mountain. Must be done ASAP when it shows up."},
  {id:'q306',name:'Payback',               type:'Main Quest',    region:'Novigrad',     from:'Wild Hunt', note:'Before completing: Final Preparations.'},
  {id:'q307',name:'The Great Escape',      type:'Main Quest',    region:'Novigrad',     from:'Wild Hunt'},
  {id:'q308',name:'Blindingly Obvious',    type:'Main Quest',    region:'Novigrad',     from:'Wild Hunt'},
  {id:'q309',name:'Reason of State',       type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'See Comment', note:'Before completing: On Thin Ice. Be careful not to beat up Dijkstra while rescuing Philippa or you lose this quest.'},
  {id:'q310',name:'It Takes Three to Tango', type:'Side Quest',  region:'Novigrad',     from:'Wild Hunt', when:'See Comment', note:'If you romanced both Triss and Yennefer.'},
  {id:'q311',name:'Final Preparations',    type:'Main Quest',    region:'Novigrad',     from:'Wild Hunt'},
  {id:'q312',name:'Through Time and Space', type:'Main Quest',   region:'Novigrad',     from:'Wild Hunt', note:'REMEMBER TO GET THE PLACE OF POWER!'},
  {id:'q313',name:'Veni Vidi Vigo',        type:'Main Quest',    region:'Skellige',     from:'Wild Hunt'},
  {id:'q314',name:'Child of the Elder Blood', type:'Main Quest', region:'Skellige',     from:'Wild Hunt'},
  {id:'q315',name:"Skjall's Grave",        type:'Main Quest',    region:'Skellige',     from:'Wild Hunt', note:'Only accessible if you make a specific choice during The Child of the Elder Blood.'},
  {id:'q316',name:'The Sunstone',          type:'Main Quest',    region:'Skellige',     from:'Wild Hunt'},
  {id:'q317',name:'Battle Preparations',   type:'Main Quest',    region:'Multiple',     from:'Wild Hunt'},
  {id:'q318',name:'On Thin Ice',           type:'Main Quest',    region:'Skellige',     from:'Wild Hunt'},
  {id:'q319',name:'Tedd Deireadh, the Final Age', type:'Main Quest', region:'Skellige', from:'Wild Hunt'},

  // ── EPILOGUE ─────────────────────────────────────────────────────
  {id:'q320',name:'Faithful Friend',       type:'Side Quest',    region:'White Orchard',from:'Wild Hunt', when:'See Comment', note:'Only available during the epilogue — Empress Ending only.'},
  {id:'q321',name:'Event: Save Tomira from Burning', type:'Event', region:'White Orchard', from:'Wild Hunt', when:'See Comment', note:'Only available during Something Ends, Something Begins in the Witcheress ending.'},
  {id:'q322',name:'Event: Meet the 5 Dwarves from Isle of Mists', type:'Event', region:'White Orchard', from:'Wild Hunt', when:'See Comment', note:"Only available during Something Ends, Something Begins in the Witcheress ending."},
  {id:'q323',name:'Something Ends, Something Begins', type:'Main Quest', region:'White Orchard', from:'Wild Hunt'},

  // ── MISC LATE NOVIGRAD ─────────────────────────────────────────────
  {id:'q324',name:'The Taxman Cometh',     type:'Side Quest',    region:'Novigrad',     from:'Hearts of Stone', note:'North-west of Oxenfurt Harbor.'},
  {id:'q325',name:'Event: The Price of Passage', type:'Event',   region:'Novigrad',     from:'Wild Hunt', when:'ASAP', note:'Near Oxenfurt — two Redanian soldiers asking for a "war tax". Triple event.'},
  {id:'q326',name:'Contract: The Oxenfurt Drunk', type:'Contract', region:'Novigrad',   from:'Wild Hunt', when:'ASAP'},
  {id:'q327',name:'Rough Neighbourhood',   type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'See Comment', note:'Becomes available after Contract: The Oxenfurt Drunk — use only your fists!'},
  {id:'q328',name:'Event: Follow-up — Dora to the Rescue', type:'Event', region:'Novigrad', from:'Wild Hunt', when:'See Comment', note:'Return to Oxenfurt a few days after "Rough Neighbourhood" — ambushed by five mercenaries.'},
  {id:'q329',name:'Contract: The Creature from Oxenfurt Forest', type:'Contract', region:'Novigrad', from:'Wild Hunt', when:'See Comment', note:'Do this now if you want extra dialogue with Hans later.'},
  {id:'q330',name:'Little Red',            type:'Side Quest',    region:'Novigrad',     from:'Wild Hunt', when:'ASAP'},
  {id:'q331',name:'Lost Goods',            type:'Treasure Hunt', region:'Velen',        from:'Wild Hunt', note:'Question mark north of Ferry Station.'},
  {id:'q332',name:'Scavenger Hunt: Griffin School Gear Upgrade Diagrams – Part 2 (alt)', type:'Treasure Hunt', region:'Velen', from:'Wild Hunt'},

  // ── HEARTS OF STONE ───────────────────────────────────────────────
  {id:'q333',name:"Evil's Soft First Touches", type:'Main Quest', region:'Novigrad',   from:'Hearts of Stone', note:'If you had the expansions installed when starting a new game, this shows up when arriving in Velen.'},
  {id:'q334',name:'Enchanting: Start-up Costs', type:'Side Quest', region:'Novigrad',  from:'Hearts of Stone'},
  {id:'q335',name:'Enchanting: Quality Has Its Price', type:'Side Quest', region:'Novigrad', from:'Hearts of Stone', note:"At the end you can pay 10,000 and 15,000 more, but it's not needed for this quest!"},
  {id:'q336',name:'Races: Swift as the Western Winds', type:'Race', region:'Novigrad', from:'Hearts of Stone'},
  {id:'q337',name:'The Cursed Chapel',     type:'Treasure Hunt', region:'Novigrad',    from:'Hearts of Stone', note:'North of Upper Mill.'},
  {id:'q338',name:'The Drakenbord Redemption', type:'Treasure Hunt', region:'Novigrad', from:'Hearts of Stone', note:'North-East of Sarrasin Grange in cave entrance.'},
  {id:'q339',name:'Tinker, Hunter, Soldier, Spy', type:'Treasure Hunt', region:'Novigrad', from:'Hearts of Stone', note:'In tower east of Isolated Hut.'},
  {id:'q340',name:'The Sword, Famine and Perfidy', type:'Treasure Hunt', region:'Novigrad', from:'Hearts of Stone'},
  {id:'q341',name:"Rose on a Red Field",   type:'Side Quest',    region:'Novigrad',    from:'Hearts of Stone'},
  {id:'q342',name:"From Ofier's Distant Shores", type:'Treasure Hunt', region:'Novigrad', from:'Hearts of Stone'},
  {id:'q343',name:'Without a Trace',       type:'Side Quest',    region:'Novigrad',    from:'Hearts of Stone'},
  {id:'q344',name:'A Dark Legacy',         type:'Treasure Hunt', region:'Novigrad',    from:'Hearts of Stone', when:'ASAP', note:'Buy the eagle statue and go to armorer to dismantle it.'},
  {id:'q345',name:'Open Sesame: Witcher Seasonings', type:'Main Quest', region:'Novigrad', from:'Hearts of Stone'},
  {id:'q346',name:'Open Sesame: The Safecracker', type:'Main Quest', region:'Novigrad', from:'Hearts of Stone'},
  {id:'q347',name:'Open Sesame: Breaking and Entering', type:'Main Quest', region:'Novigrad', from:'Hearts of Stone', note:'Go to Hugo first.'},
  {id:'q348',name:'Open Sesame!',          type:'Main Quest',    region:'Novigrad',    from:'Hearts of Stone', note:'BUY THE WITCHER GEAR FROM MIGNOLE, BUY THE EAGLE STATUE (A Dark Legacy) AND TALK TO THE ART CONNOISSEUR (Avid Collector)! ALSO LOOT THE VAULT FOR GEAR.'},
  {id:'q349',name:'The Secret Life of Count Romilly', type:'Treasure Hunt', region:'Novigrad', from:'Hearts of Stone'},
  {id:'q350',name:'A Surprise Inheritance', type:'Treasure Hunt', region:'Novigrad',   from:'Hearts of Stone', note:'North of Heddel.'},
  {id:'q351',name:'The Royal Air Force',   type:'Treasure Hunt', region:'Novigrad',    from:'Hearts of Stone', note:'North-east of Est Tayiar in ruins of castle.'},
  {id:'q352',name:'A Midnight Clear',      type:'Side Quest',    region:'Novigrad',    from:'Hearts of Stone', when:'ASAP'},
  {id:'q353',name:"Dead Man's Party",      type:'Main Quest',    region:'Novigrad',    from:'Hearts of Stone', note:"To do all activities and get the achievement, leave one of the mandatory ones last. I'd leave the Shani shoe fishing one till last."},
  {id:'q354',name:'Scenes From a Marriage', type:'Main Quest',   region:'Novigrad',    from:'Hearts of Stone', note:"YOU PROBABLY SHOULDN'T USE THE PAINTING FOR THE BURIAL IF YOU WANT IT AT CORVO BIANCO."},
  {id:'q355',name:'Whatsoever a Man Soweth', type:'Main Quest',  region:'Novigrad',    from:'Hearts of Stone', note:'GET THE WITCHER GEAR IF YOU HELP.'},
  {id:'q356',name:'Avid Collector',        type:'Side Quest',    region:'Novigrad',    from:'Hearts of Stone', when:'ASAP', note:'HANG THE PAINTING IN CORVO BIANCO BEFORE SELLING IT!'},

  // ── BLOOD AND WINE ────────────────────────────────────────────────
  {id:'q357',name:'Envoys, Wineboys',      type:'Main Quest',    region:'Velen',       from:'Blood and Wine'},
  {id:'q358',name:'Event: Lost Engagement Ring', type:'Event',   region:'Toussaint',   from:'Blood and Wine', when:'ASAP', note:'No exclamation mark! South of Beauclair Palace — woman crying on a small bridge. Find ring at bottom of river.'},
  {id:'q359',name:'The Beast of Toussaint', type:'Main Quest',   region:'Toussaint',   from:'Blood and Wine', note:'Shoot Golyat in the eye for an achievement.'},
  {id:'q360',name:'Blood Run',             type:'Main Quest',    region:'Toussaint',   from:'Blood and Wine', note:'RETURN TO THE GREENHOUSE TO GET THE HARE MASK!'},
  {id:'q361',name:'No Place Like Home (B&W)', type:'Side Quest', region:'Toussaint',   from:'Blood and Wine', when:'ASAP', note:'Unlocked during "The Beast of Toussaint".'},
  {id:'q362',name:'Extreme Cosplay',       type:'Side Quest',    region:'Toussaint',   from:'Blood and Wine', when:'ASAP', note:'Exclamation mark between Mere-Lachaislongue Cemetery and Trestamara Hunting Lodge.'},
  {id:'q363',name:'Turn and Face the Strange', type:'Side Quest', region:'Toussaint',  from:'Blood and Wine', note:'Exclamation mark near The Gran Palace. Option to earn "There Can Only Be One" — give the child coin (Generosity).'},
  {id:'q364',name:'Scavenger Hunt: Grandmaster Griffin Gear', type:'Treasure Hunt', region:'Toussaint', from:'Blood and Wine'},
  {id:'q365',name:'Goodness Gracious Great Balls of Granite', type:'Side Quest', region:'Toussaint', from:'Blood and Wine'},
  {id:'q366',name:'Fists of Fury: Toussaint', type:'Side Quest', region:'Toussaint',   from:'Blood and Wine'},
  {id:'q367',name:'Father Knows Worst',    type:'Side Quest',    region:'Toussaint',   from:'Blood and Wine'},
  {id:'q368',name:'Raging Wolf',           type:'Side Quest',    region:'Toussaint',   from:'Blood and Wine'},
  {id:'q369',name:'The Warble of a Smitten Knight', type:'Side Quest', region:'Toussaint', from:'Blood and Wine', when:'See Comment', note:'Option to earn "There Can Only Be One" — multiple choices for Honor and Valor. Must be done before "Capture the Castle".'},
  {id:'q370',name:'There Can Be Only One', type:'Side Quest',    region:'Toussaint',   from:'Blood and Wine', when:'ASAP'},
  {id:'q371',name:'The Toussaint Prison Experiment', type:'Treasure Hunt', region:'Toussaint', from:'Blood and Wine', note:'Question mark west of Fort Astre Ruins.'},
  {id:'q372',name:'The Words of the Prophet Are Written on Sarcophagi', type:'Side Quest', region:'Toussaint', from:'Blood and Wine', note:"Loot Bones of the Great Beggar's in the Temple near Prophet Lebioda Statue."},
  {id:'q373',name:'Scavenger Hunt: Grandmaster Manticore Gear', type:'Treasure Hunt', region:'Toussaint', from:'Blood and Wine'},
  {id:'q374',name:'Master, Master, Master, Master', type:'Side Quest', region:'Toussaint', from:'Blood and Wine'},
  {id:'q375',name:'La Cage au Fou',        type:'Main Quest',    region:'Toussaint',   from:'Blood and Wine', note:'Option to earn "There Can Only Be One" — thoroughly explore the Wight\'s Lair and try to lift the curse instead of attacking.'},
  {id:'q376',name:"Amidst the Mill's Grist", type:'Side Quest',  region:'Toussaint',   from:'Blood and Wine', when:'ASAP BUT', note:'Unlocks after you took the ritual in "La Cage au Fou". Visit the mill before going to the boat.'},
  {id:'q377',name:'The Suffering of Young François', type:'Treasure Hunt', region:'Toussaint', from:'Blood and Wine', note:'Question mark in Fort Astre Ruins.'},
  {id:'q378',name:'Spoontaneous Profits',  type:'Treasure Hunt', region:'Toussaint',   from:'Blood and Wine', note:"Read a note attached to one of the spoons during 'La Cage au Fou'."},
  {id:'q379',name:'Where Children Toil, Toys Waste Away', type:'Main Quest', region:'Toussaint', from:'Blood and Wine'},
  {id:'q380',name:'Wine is Sacred',        type:'Main Quest',    region:'Toussaint',   from:'Blood and Wine'},
  {id:'q381',name:'Scavenger Hunt: Grandmaster Wolven Gear', type:'Treasure Hunt', region:'Toussaint', from:'Blood and Wine'},
  {id:'q382',name:'Event: Contract on a Witcher', type:'Event', region:'Toussaint',    from:'Blood and Wine', when:'ASAP', note:"Event triggers after 'Wine is Sacred'."},
  {id:'q383',name:'The Man from Cintra',   type:'Main Quest',    region:'Toussaint',   from:'Blood and Wine'},
  {id:'q384',name:'The Hunger Game',       type:'Side Quest',    region:'Toussaint',   from:'Blood and Wine', note:'Triggers a few days at Corvo Bianco after peacefully resolving a confrontation during "La Cage au Fou".'},
  {id:'q385',name:'Scavenger Hunt: Grandmaster Ursine Gear', type:'Treasure Hunt', region:'Toussaint', from:'Blood and Wine'},
  {id:'q386',name:'Contract: Bovine Blues', type:'Contract',     region:'Toussaint',   from:'Blood and Wine'},
  {id:'q387',name:'The Black Widow',       type:'Treasure Hunt', region:'Toussaint',   from:'Blood and Wine', note:'Question mark west of Flovive.'},
  {id:'q388',name:'Big Feet to Fill: The 1st Group', type:'Side Quest', region:'Toussaint', from:'Blood and Wine', note:'North east of Fox Hollow.'},
  {id:'q389',name:'Big Feet to Fill: The 2nd Group', type:'Side Quest', region:'Toussaint', from:'Blood and Wine', note:"South West of Plegmund's Bridge."},
  {id:'q390',name:'Big Feet to Fill: The 3rd Group', type:'Side Quest', region:'Toussaint', from:'Blood and Wine', note:'North of Castel Ravello Vineyard at the right bridge with a pack of wolves.'},
  {id:'q391',name:'Big Feet to Fill: The 4th Group', type:'Side Quest', region:'Toussaint', from:'Blood and Wine', note:'East of The Silver Salamander Inn.'},
  {id:'q392',name:'Big Feet to Fill: The 5th Group', type:'Side Quest', region:'Toussaint', from:'Blood and Wine', note:'North of Prophet Lebioda Statue.'},
  {id:'q393',name:"Don't Take Candy from a Stranger", type:'Treasure Hunt', region:'Toussaint', from:'Blood and Wine', note:'Question mark south-west of Prophet Lebioda Statue.'},
  {id:'q394',name:'What Was This About Again?', type:'Treasure Hunt', region:'Toussaint', from:'Blood and Wine', note:'Question mark in river north east of prophet lebioda statue.'},
  {id:'q395',name:'Big Feet to Fill',      type:'Side Quest',    region:'Toussaint',   from:'Blood and Wine'},
  {id:'q396',name:'The Curse of Carnarvon', type:'Treasure Hunt', region:'Toussaint',  from:'Blood and Wine', note:'Question mark east of Castel Ravello Vineyard.'},
  {id:'q397',name:'Wine Wars: Belgaard (Part 1)', type:'Side Quest', region:'Toussaint', from:'Blood and Wine', when:'ASAP', note:'Unlocks after Wine Wars: Consorting.'},
  {id:'q398',name:'Wine Wars: Coronata',   type:'Side Quest',    region:'Toussaint',   from:'Blood and Wine', when:'See Comment', note:'Do NOT finish this quest — read notes you find during Coronata and Vermentino and do Wine Wars: The Dues in the Machina first!'},
  {id:'q399',name:'Wine Wars: Vermentino', type:'Side Quest',    region:'Toussaint',   from:'Blood and Wine', when:'See Comment', note:'Do NOT finish this quest — read notes and do Wine Wars: The Dues in the Machina first!'},
  {id:'q400',name:'Wine Wars: The Dues in the Machina', type:'Side Quest', region:'Toussaint', from:'Blood and Wine', when:'ASAP BUT', note:'Unlocks if you read the notes during Coronata and Vermentino. Do NOT complete the other Wine Wars quests before this one!'},
  {id:'q401',name:'Wine Wars: Consorting', type:'Side Quest',    region:'Toussaint',   from:'Blood and Wine', when:'ASAP', note:"After completing Wine Wars: The Dues in the Machina, go to the NPCs near Plegmund's Bridge."},
  {id:'q402',name:'Wine Wars: Belgaard (Part 2)', type:'Side Quest', region:'Toussaint', from:'Blood and Wine', when:'ASAP', note:'Unlocks after Wine Wars: Consorting.'},
  {id:'q403',name:'Scavenger Hunt: Grandmaster Feline Gear', type:'Treasure Hunt', region:'Toussaint', from:'Blood and Wine'},
  {id:'q404',name:'Around the World in... Eight Days', type:'Treasure Hunt', region:'Toussaint', from:'Blood and Wine', note:'Question mark east of Coronata Vineyard.'},
  {id:'q405',name:"Mutual of Beauclair's Wild Kingdom", type:'Side Quest', region:'Toussaint', from:'Blood and Wine'},
  {id:'q406',name:"A Knight's Tales",      type:'Side Quest',    region:'Toussaint',   from:'Blood and Wine'},
  {id:'q407',name:"Vitner's Contract: Chuchote Cave", type:'Side Quest', region:'Toussaint', from:'Blood and Wine', note:'Question mark west of Castel Ravello Vineyard.'},
  {id:'q408',name:"Event: Grave Robbers 'Visiting Grandpa'", type:'Event', region:'Toussaint', from:'Blood and Wine', when:'ASAP', note:"Part of 'Till Death Do You Part' depending on your choice."},
  {id:'q409',name:'Till Death Do You Part', type:'Side Quest',   region:'Toussaint',   from:'Blood and Wine', when:'ASAP'},
  {id:'q410',name:"The Last Exploits of Selina's Gang", type:'Treasure Hunt', region:'Toussaint', from:'Blood and Wine', when:'ASAP', note:'Question mark at the banks of The Old Cemetery.'},
  {id:'q411',name:'Of Sheers and a Witcher I Sing', type:'Side Quest', region:'Toussaint', from:'Blood and Wine', note:"Exclamation mark north west of Lebioda's Gate."},
  {id:'q412',name:'Paperchase',            type:'Side Quest',    region:'Toussaint',   from:'Blood and Wine', note:'Exclamation mark near armorer and blacksmith in Beauclair.'},
  {id:'q413',name:'A Portrait of the Witcher as an Old Man', type:'Side Quest', region:'Toussaint', from:'Blood and Wine', note:'South of The Gran Palace on the south side of the market square.'},
  {id:'q414',name:'But Other Than That, How Did You Enjoy the Play?', type:'Treasure Hunt', region:'Toussaint', from:'Blood and Wine'},
  {id:'q415',name:'The Inconstant Gardener', type:'Treasure Hunt', region:'Toussaint',  from:'Blood and Wine', note:'Question mark south-west of Tesham Mutna Ruins.'},
  {id:'q416',name:"Vitner's Contract: Cleaning Those Hard-To-Reach Places", type:'Side Quest', region:'Toussaint', from:'Blood and Wine', note:'Question mark north of Gelenser Farm.'},
  {id:'q417',name:'Waiting for Goe and Doh', type:'Treasure Hunt', region:'Toussaint', from:'Blood and Wine', note:'Question mark south-east of Casteldaccia abandoned estate.'},
  {id:'q418',name:'Filibert Always Pays His Debts', type:'Treasure Hunt', region:'Toussaint', from:'Blood and Wine'},
  {id:'q419',name:'Contract: Equine Phantoms', type:'Contract',  region:'Toussaint',   from:'Blood and Wine', note:'Exclamation mark on a road leading north east from Dun Tynne Crossroads.'},
  {id:'q420',name:"Coin Doesn't Stink",    type:'Treasure Hunt', region:'Toussaint',   from:'Blood and Wine', note:"Question mark north-west bridge from Dun Tynne Crossroads."},
  {id:'q421',name:"Vitner's Contract: Rivecalme Storehouse", type:'Side Quest', region:'Toussaint', from:'Blood and Wine', note:'Question mark west of Dulcinea Windmill.'},
  {id:'q422',name:"Vitner's Contract: Griffin-in-the-Vines", type:'Side Quest', region:'Toussaint', from:'Blood and Wine', note:'Question mark south-east of Rioux-Cannes outpost.'},
  {id:'q423',name:'Contract: Feet as Cold as Ice', type:'Contract', region:'Toussaint', from:'Blood and Wine', note:'You can also find François sleeping close to Grottore\'s Cave.'},
  {id:'q424',name:'Capture the Castle',    type:'Main Quest',    region:'Toussaint',   from:'Blood and Wine', note:'Point of no return: The Warble of a Smitten Knight.'},
  {id:'q425',name:'Blood Simple (branch 1 & 2)', type:'Main Quest', region:'Toussaint', from:'Blood and Wine', when:'See Comment', note:'Optional in story branch 1. Mandatory for story branch 2.'},
  {id:'q426',name:'What Lies Unseen (branch 2)', type:'Main Quest', region:'Toussaint', from:'Blood and Wine', when:'See Comment', note:'Only available in story branch 2.'},
  {id:'q427',name:'The Night of Long Fangs', type:'Main Quest',  region:'Toussaint',   from:'Blood and Wine'},
  {id:'q428',name:'Duck, Duck, Goosed!',   type:'Side Quest',    region:'Toussaint',   from:'Blood and Wine', when:'ASAP', note:'MAKE SURE YOU EAT THE GOLDEN EGG BEFORE LEAVING!'},
  {id:'q429',name:'Beyond Hill and Dale (branch 1)', type:'Main Quest', region:'Toussaint', from:'Blood and Wine', when:'See Comment', note:'Only available in story branch 1.'},
  {id:'q430',name:'Tesham Mutna',          type:'Main Quest',    region:'Toussaint',   from:'Blood and Wine'},
  {id:'q431',name:'The Perks of Being a Jailbird', type:'Side Quest', region:'Toussaint', from:'Blood and Wine', when:'See Comment', note:'Only available in story branch 1 during "Burlap is the New Stripe". Examine the loose stone on the wall at the start.'},
  {id:'q432',name:'Burlap is the New Stripe', type:'Main Quest', region:'Toussaint',   from:'Blood and Wine', when:'See Comment', note:"If you did not return Syanna's ribbon in Beyond Hill and Dale."},
  {id:'q433',name:'Event: Naughty Feathers', type:'Event', region:'Toussaint',         from:'Blood and Wine', when:'See Comment', note:'Unlocks after you finished Blood & Wine.'},
  {id:'q434',name:'Event: Meet Vivienne in Novigrad', type:'Event', region:'Novigrad', from:'Blood and Wine', when:'See Comment', note:'To get this ending, choose to lift her curse without the help of Guillaume.'},
  {id:'q435',name:'Pomp and Strange Circumstances', type:'Main Quest', region:'Toussaint', from:'Blood and Wine', when:'See Comment', note:"If you returned Syanna's ribbon in Beyond Hill and Dale or if you played What Lies Unseen."},
  {id:'q436',name:'Applied Escapology',    type:'Treasure Hunt', region:'Toussaint',   from:'Blood and Wine', note:'Question mark north west of Toussaint Prison.'},
  {id:'q437',name:"Vitner's Contract: Dun Tynne Hillside", type:'Side Quest', region:'Toussaint', from:'Blood and Wine', note:'Question mark west of Dun Tynne Crossroads.'},
  {id:'q438',name:'Contract: Big Game Hunter', type:'Contract',  region:'Toussaint',   from:'Blood and Wine'},
  {id:'q439',name:'Contract: The Tufo Monster', type:'Contract', region:'Toussaint',   from:'Blood and Wine'},
  {id:'q440',name:"Gwent: Never Fear, Skellige's Here", type:'Side Quest', region:'Toussaint', from:'Blood and Wine'},
  {id:'q441',name:'Gwent: To Everything – Turn, Turn, Tournament', type:'Side Quest', region:'Toussaint', from:'Blood and Wine'},
  {id:'q442',name:'Knight for Hire',       type:'Side Quest',    region:'Toussaint',   from:'Blood and Wine'},
  {id:'q443',name:'Be It Ever So Humble',  type:'Main Quest',    region:'Toussaint',   from:'Blood and Wine'},
  {id:'q444',name:'Event: Death by the Unseen Elder', type:'Event', region:'Toussaint', from:'Blood and Wine', note:"You can find the Unseen Elder (and face death) when you got the key to the cave from Orianna during Blood Simple, even after completing branch 1."},
];

/* ═══ QUEST → ACHIEVEMENT LINKS ═══
   Story-related and missable achievements tied to specific quests.
   Each entry: questId → [achId, ...]
*/
const QUEST_ACHIEVEMENTS = {
  'q2':   ['ach_lilac_and_gooseberries'],
  'q19':  ['ach_family_counselor'],
  'q20':  ['ach_family_counselor'],
  'q25':  ['ach_shrieker'],
  'q86':  ['ach_woodland_spirit'],
  'q104': ['ach_friend_in_need'],
  'q123': ['ach_friend_in_need'],
  'q157': ['ach_fearless_vampire_slayer'],
  'q183': ['ach_necromancer'],
  'q201': ['ach_something_more'],
  'q208': ['ach_kingmaker'],
  'q209': ['ach_kingmaker'],
  'q247': ['ach_assassin_of_kings'],
  'q246': ['ach_friends_with_benefits'],
  'q300': ['ach_something_more'],
  'q301': ['ach_full_crew'],
  'q302': ['ach_xenonaut'],
  'q313': ['ach_xenonaut'],
  'q318': ['ach_the_king_is_dead'],
  'q319': ['ach_the_king_is_dead'],
  'q323': ['ach_something_more'],
  'q348': ['ach_shopaholic'],
  'q353': ['ach_let_the_good_times_roll'],
  'q354': ['ach_curator_of_nightmares', 'ach_when_its_many_against_one'],
  'q355': ['ach_pacta_sunt_servanda'],
  'q359': ['ach_david_and_golyat'],
  'q369': ['ach_a_knight_to_remember'],
  'q370': ['ach_embodiment_of_five_virtues'],
  'q375': ['ach_grapes_of_wrath'],
  'q401': ['ach_grapes_of_wrath'],
  'q327': ['ach_kling_of_the_clink'],
  'q357': ['ach_witcher_gone_south'],
  'q369': ['ach_last_action_hero'],
};

/* ═══ ACHIEVEMENTS (Steam Achievements) ═══ */
const ACHIEVEMENTS = [
  // ── STORY-RELATED (shown on quests tab too) ──────────────────────
  {id:'ach_lilac_and_gooseberries', name:'Lilac and Gooseberries', type:'bronze', secret:true, category:'Story', desc:'Find Yennefer of Vengerberg. (Automatic during story.)'},
  {id:'ach_friend_in_need',   name:'A Friend in Need',        type:'bronze', secret:true, category:'Story', desc:'Find and free Dandelion. (Automatic during story.)'},
  {id:'ach_necromancer',      name:'Necromancer',             type:'bronze', secret:true, category:'Story', desc:"Help Yennefer extract information from Skjall's body. (Automatic during story.)"},
  {id:'ach_family_counselor', name:'Family Counselor',        type:'bronze', secret:true, category:'Story', desc:"Find the Baron's wife and daughter. (Automatic during story.)"},
  {id:'ach_something_more',   name:'Something More',          type:'bronze', secret:true, category:'Story', desc:'Find Ciri. (Automatic during story.)'},
  {id:'ach_xenonaut',         name:'Xenonaut',                type:'bronze', secret:true, category:'Story', desc:"Visit Tir ná Lia and convince Ge'els to betray Eredin. (Automatic during story.)"},
  {id:'ach_the_king_is_dead', name:'The King is Dead',        type:'silver', secret:true, category:'Story', desc:'Defeat Eredin. (Automatic during story.)'},
  {id:'ach_im_not_kissing_that', name:"I'm Not Kissing That", type:'bronze', secret:true, category:'Story — Hearts of Stone', desc:'Kill the prince cursed into a toad. (During Hearts of Stone story.)'},
  {id:'ach_pacta_sunt_servanda', name:'Pacta Sunt Servanda',  type:'bronze', secret:true, category:'Story — Hearts of Stone', desc:'Finish the "Hearts of Stone" expansion. (Automatic.)'},
  {id:'ach_witcher_gone_south', name:"The Witcher's Gone South", type:'bronze', secret:false, category:'Story — Blood and Wine', desc:'Travel to the Duchy of Toussaint. (Automatic on first arrival.)'},

  // ── MISSABLE ─────────────────────────────────────────────────────
  {id:'ach_geralt_professional', name:'Geralt: The Professional', type:'bronze', secret:true, category:'Missable', desc:'Complete ALL witcher contracts in the game. Track your progress on the Quests tab.'},
  {id:'ach_kingmaker',      name:'Kingmaker',               type:'bronze', secret:true, category:'Missable', desc:"Complete the subplot about choosing Skellige's ruler. Do King's Gambit + Coronation before Isle of Mists."},
  {id:'ach_assassin_of_kings', name:'Assassin of Kings',   type:'bronze', secret:true, category:'Missable', desc:'Take part in the assassination of King Radovid. Complete "A Deadly Plot" and "Reason of State".'},
  {id:'ach_friends_with_benefits', name:'Friends With Benefits', type:'bronze', secret:true, category:'Missable', desc:'Complete the subplot involving Keira Metz. Do all her quests and send her to Kaer Morhen.'},
  {id:'ach_full_crew',      name:'Full Crew',               type:'bronze', secret:true, category:'Missable', desc:'Bring all possible allies to Kaer Morhen for the battle. Complete all related side quests before Isle of Mists.'},
  {id:'ach_even_odds',      name:'Even Odds',               type:'silver', secret:false, category:'Missable', desc:'Kill 2 monsters you have a contract on without using Signs, potions, mutagens, oils or bombs.'},
  {id:'ach_card_collector', name:'Card Collector',          type:'bronze', secret:false, category:'Missable', desc:'Acquire all Gwent cards available in the base game. Complete all Gwent quests.'},
  {id:'ach_gwent_master',   name:'Gwent Master',            type:'bronze', secret:false, category:'Missable', desc:'Defeat Tybalt and win the Gwent tournament at the Passiflora. (High Stakes quest.)'},
  {id:'ach_brawl_master',   name:'Brawl Master',            type:'bronze', secret:false, category:'Missable', desc:'Complete all fistfighting quests in Velen, Skellige and Novigrad.'},
  {id:'ach_fast_and_furious', name:'Fast and Furious',      type:'bronze', secret:false, category:'Missable', desc:'Win all the horse races in the game.'},
  {id:'ach_fist_of_south_star', name:'Fist of the South Star', type:'bronze', secret:false, category:'Missable', desc:'Defeat an opponent in a fistfight without taking any damage.'},
  {id:'ach_woodland_spirit', name:'Woodland Spirit',        type:'bronze', secret:true, category:'Missable', desc:'Complete the contract on the Woodland Spirit. (Contract: Woodland Beast in Velen.)'},
  {id:'ach_let_the_good_times_roll', name:"Let the Good Times Roll!", type:'bronze', secret:true, category:'Missable — Hearts of Stone', desc:"Participate in ALL activities at the wedding during Dead Man's Party."},
  {id:'ach_shopaholic',     name:'Shopaholic',              type:'bronze', secret:true, category:'Missable — Hearts of Stone', desc:"Buy ALL items put on the block at the Borsodis' Auction House during Open Sesame."},
  {id:'ach_curator_of_nightmares', name:'Curator of Nightmares', type:'bronze', secret:true, category:'Missable — Hearts of Stone', desc:"Recreate ALL of Iris' nightmares in the Painted World (Scenes From a Marriage)."},
  {id:'ach_when_its_many_against_one', name:"When It's Many Against One…", type:'bronze', secret:true, category:'Missable — Hearts of Stone', desc:"Provoke ALL of Iris von Everec's Nightmares into fighting you simultaneously and defeat them."},
  {id:'ach_last_action_hero', name:'Last Action Hero',      type:'bronze', secret:false, category:'Missable — Blood and Wine', desc:'Be decorated with the Order of Vitis Vinifera. Earn the decoration during the tournament storyline.'},
  {id:'ach_kling_of_the_clink', name:'Kling of the Clink', type:'bronze', secret:false, category:'Missable — Blood and Wine', desc:'Serve time in Toussaint. Get arrested during Blood and Wine story.'},
  {id:'ach_a_knight_to_remember', name:'A Knight to Remember', type:'bronze', secret:false, category:'Missable — Blood and Wine', desc:"Obtain a flawless victory in all competitions during the knights' tourney (The Warble of a Smitten Knight)."},
  {id:'ach_embodiment_of_five_virtues', name:'Embodiment of the Five Virtues', type:'bronze', secret:false, category:'Missable — Blood and Wine', desc:'Be given Aerondight by the Lady of the Lake. (Complete "There Can Be Only One" demonstrating all 5 virtues.)'},
  {id:'ach_grapes_of_wrath', name:'The Grapes of Wrath Stomped', type:'bronze', secret:true, category:'Missable — Blood and Wine', desc:'Help unite the warring vineyards and have a wine named in your honor. (Wine Wars questline.)'},
  {id:'ach_david_and_golyat', name:'David and Golyat',      type:'bronze', secret:true, category:'Missable — Blood and Wine', desc:'Kill Golyat with a crossbow bolt to his eye (during "The Beast of Toussaint").'},

  // ── COMBAT / GENERAL ────────────────────────────────────────────
  {id:'ach_dendrologist',   name:'Dendrologist',            type:'bronze', secret:false, category:'Combat & Skills', desc:'Acquire all abilities in one skill tree.'},
  {id:'ach_enemy_of_enemy', name:'The Enemy of My Enemy',   type:'bronze', secret:false, category:'Combat & Skills', desc:'Use the Axii Sign to force one opponent to kill another. Do this 20 times.'},
  {id:'ach_humpty_dumpty',  name:'Humpty Dumpty',           type:'bronze', secret:false, category:'Combat & Skills', desc:'Kill 10 opponents by knocking them off somewhere high with the Aard Sign.'},
  {id:'ach_env_unfriendly', name:'Environmentally Unfriendly', type:'bronze', secret:false, category:'Combat & Skills', desc:'Kill 50 opponents using the environment (swamp gas, insects, objects).'},
  {id:'ach_kaer_morhen_trained', name:'Kaer Morhen Trained', type:'bronze', secret:false, category:'Combat & Skills', desc:'Perform 10 effective counterattacks in a row without getting hit or parrying.'},
  {id:'ach_cant_touch_this', name:"Can't Touch This!",      type:'bronze', secret:false, category:'Combat & Skills', desc:'Kill 5 foes in a fight without taking damage (except Toxicity) and without using Quen.'},
  {id:'ach_that_is_evilest', name:'That Is the Evilest Thing…', type:'bronze', secret:false, category:'Combat & Skills', desc:"Ignite the gas produced by a Dragon's Dream bomb using a burning opponent. Do this 10 times."},
  {id:'ach_mutant',         name:'Mutant',                  type:'bronze', secret:false, category:'Combat & Skills', desc:'Fill all mutagen slots.'},
  {id:'ach_butcher_blaviken', name:'Butcher of Blaviken',   type:'silver', secret:false, category:'Combat & Skills', desc:'Kill at least 5 opponents in under 10 seconds.'},
  {id:'ach_brawler',        name:'Brawler',                 type:'silver', secret:false, category:'Combat & Skills', desc:'Defeat Olaf, the Skellige champion of unarmed combat.'},
  {id:'ach_overkill',       name:'Overkill',                type:'silver', secret:false, category:'Combat & Skills', desc:'Make an opponent suffer from bleeding, poisoning and burning simultaneously. Do this 10 times.'},
  {id:'ach_master_marksman', name:'Master Marksman',        type:'bronze', secret:false, category:'Combat & Skills', desc:'Kill 50 human and nonhuman opponents by striking them in the head with a crossbow bolt.'},
  {id:'ach_triple_threat',  name:'Triple Threat',           type:'bronze', secret:true, category:'Combat & Skills', desc:'Kill 3 opponents in one fight using 3 different methods (swords, bombs, crossbow, Signs, etc.).'},
  {id:'ach_what_was_that',  name:'What Was That?',          type:'bronze', secret:true, category:'Combat & Skills', desc:'Attack, counter, cast a Sign and throw a bomb (in any order) in under 4 seconds.'},
  {id:'ach_shrieker',       name:'Shrieker',                type:'bronze', secret:true, category:'Combat & Skills', desc:'Complete the contract on the shrieker. (Contract: Shrieker in Velen.)'},
  {id:'ach_fearless_vampire_slayer', name:'Fearless Vampire Slayer', type:'bronze', secret:true, category:'Combat & Skills', desc:'Complete the contract on Sarasti. (Contract: Deadly Delights in Novigrad.)'},
  {id:'ach_fiend_or_foe',   name:'Fiend or Foe?',           type:'bronze', secret:true, category:'Combat & Skills', desc:'Complete the contract on Morvudd. (Contract: Muire D\'yaeblen in Skellige.)'},
  {id:'ach_ashes_to_ashes', name:'Ashes to Ashes',          type:'bronze', secret:true, category:'Combat & Skills', desc:'Complete the contract on Therazane. (Contract: The Apiarian Phantom in Novigrad.)'},
  {id:'ach_the_doppler_effect', name:'The Doppler Effect',  type:'bronze', secret:true, category:'Combat & Skills', desc:'Resolve the doppler problem in Novigrad. (Contract: An Elusive Thief.)'},
  {id:'ach_return_to_sender', name:'Return to Sender',      type:'bronze', secret:false, category:'Combat & Skills — Hearts of Stone', desc:'Kill 3 opponents with their own arrows.'},
  {id:'ach_can_quit_anytime', name:'Can Quit Anytime I Want', type:'bronze', secret:false, category:'Combat & Skills — Hearts of Stone', desc:'Be under the influence of seven potions or decoctions at the same time.'},
  {id:'ach_rad_steez',      name:'Rad Steez, Bro!',         type:'bronze', secret:true, category:'Combat & Skills — Hearts of Stone', desc:'Slide downhill uninterrupted for at least 10 seconds.'},
  {id:'ach_hasta_la_vista', name:'Hasta la Vista',          type:'bronze', secret:true, category:'Combat & Skills — Blood and Wine', desc:'Kill a frozen opponent with a crossbow bolt.'},
  {id:'ach_weapon_w',       name:'Weapon "W"',              type:'bronze', secret:false, category:'Combat & Skills — Blood and Wine', desc:'Develop a mutation.'},

  // ── EXPLORATION / COLLECTION ────────────────────────────────────
  {id:'ach_globetrotter',   name:'Globetrotter',            type:'bronze', secret:false, category:'Exploration', desc:'Discover 100 fast travel points.'},
  {id:'ach_pest_control',   name:'Pest Control',            type:'silver', secret:false, category:'Exploration', desc:'Destroy all monster nests in the Velen/Novigrad region, or in Skellige.'},
  {id:'ach_lets_cook',      name:"Let's Cook!",             type:'bronze', secret:false, category:'Exploration', desc:'Learn 12 potion formulae.'},
  {id:'ach_bombardier',     name:'Bombardier',              type:'bronze', secret:false, category:'Exploration', desc:'Collect the formulae for 6 different bomb types.'},
  {id:'ach_bookworm',       name:'Bookworm',                type:'bronze', secret:false, category:'Exploration', desc:'Read 30 books, journals or other documents.'},
  {id:'ach_armed_dangerous', name:'Armed and Dangerous',    type:'silver', secret:false, category:'Exploration', desc:'Find and equip all elements of one set of witcher gear.'},
  {id:'ach_power_overwhelming', name:'Power Overwhelming',  type:'bronze', secret:false, category:'Exploration', desc:'Have all possible Place of Power bonuses active at the same time.'},
  {id:'ach_fire_in_hole',   name:'Fire in the Hole',        type:'bronze', secret:false, category:'Exploration', desc:'Destroy 10 monster nests using bombs.'},
  {id:'ach_geralt_friends', name:'Geralt and Friends',      type:'bronze', secret:false, category:'Exploration', desc:'Win a round of Gwent using only neutral cards.'},
  {id:'ach_all_in',         name:'All In',                  type:'bronze', secret:false, category:'Exploration', desc:'Play three hero cards in one round of Gwent and win the match.'},
  {id:'ach_munchkin',       name:'Munchkin',                type:'gold', secret:false, category:'Exploration', desc:'Reach character development level 35.'},
  {id:'ach_wild_rose_dethorned', name:'Wild Rose Dethorned', type:'bronze', secret:false, category:'Exploration — Hearts of Stone', desc:'Defeat all the fallen knights and loot their campsites.'},
  {id:'ach_i_wore_ofieri',  name:'I Wore Ofieri Before It Was Cool', type:'bronze', secret:false, category:'Exploration — Hearts of Stone', desc:'Collect all available Ofieri armor and horse gear, and at least one Ofieri sword.'},
  {id:'ach_killed_it',      name:'Killed It',               type:'bronze', secret:false, category:'Exploration — Hearts of Stone', desc:'Win a round of Gwent with a total strength of at least 187.'},
  {id:'ach_moo_rderer',     name:'Moo-rderer',              type:'bronze', secret:true, category:'Exploration — Hearts of Stone', desc:'Kill 20 cows. (Note: Devil\'s Pit enemies respawn — you can get most non-missable achievements there!)'},
  {id:'ach_playing_house',  name:'Playing House',           type:'bronze', secret:false, category:'Exploration — Blood and Wine', desc:'Use all available options for developing Corvo Bianco.'},
  {id:'ach_turned_every_stone', name:'Turned Every Stone',  type:'bronze', secret:false, category:'Exploration — Blood and Wine', desc:'Find all grandmaster diagrams for each witcher school.'},
  {id:'ach_i_have_gwent_problem', name:'I Have a Gwent Problem', type:'bronze', secret:false, category:'Exploration — Blood and Wine', desc:'Collect all the cards in the Skellige deck.'},
  {id:'ach_dressed_to_kill', name:'Dressed to Kill',        type:'bronze', secret:false, category:'Exploration — Blood and Wine', desc:'Unlock the bonus for equipping all the witcher gear elements from one School.'},

  // ── DIFFICULTY ─────────────────────────────────────────────────
  {id:'ach_passed_the_trial', name:'Passed the Trial',      type:'bronze', secret:false, category:'Difficulty', desc:'Finish the game on any difficulty.'},
  {id:'ach_ran_gauntlet',   name:'Ran the Gauntlet',        type:'silver', secret:false, category:'Difficulty', desc:'Finish the game on "Blood and Broken Bones!" or "Death March!" difficulty.'},
  {id:'ach_walked_the_path', name:'Walked the Path',        type:'gold', secret:false, category:'Difficulty', desc:'Finish the game on "Death March!" difficulty level.'},

  // ── PLATINUM ───────────────────────────────────────────────────
  {id:'ach_platinum',       name:'The Limits of the Possible', type:'platinum', secret:false, category:'Platinum', desc:'Collect all achievements.'},
];
